version: '3'
services:
    timeliner:
        container_name: timeliner
        image: 'thinkfree84/timeliner'
        build:
                context: ./
                dockerfile: Dockerfile
        ports:
            - 0.0.0.0:8080:8080
        volumes:
            - ./:/app/

